### ISSUE TITLE
Turn off the camera when going to another page

### ISSUE THREAD

**Issue by florianEnoh** [yoyota/react-posenet#15]
Hi,
When i load the component in my page it works fine, thank you for this amazing module.
But i don't catch how to switch off the camera when i navigate to a new page, the camera stays on. 
Could you help me ?

**Comment by florianEnoh** [comment]
> Hi,
> When i load the component in my page it works fine, thank you for this amazing module.
> But i don't catch how to switch off the camera when i navigate to a new page, the camera stays on.
> Could you help me ?

When my component will unmount i do that :
```
useEffect(() => {
    function turnOffWebCam(){
      const video = document.querySelector('video');
      const mediaStream = video.srcObject;
      const tracks = mediaStream.getTracks();
      tracks.forEach(track => track.stop())
    }
    return () => turnOffWebCam()
  }, [])
```
And it works fine !

**Comment by yoyota** [comment]
Hello and Thanks for reporting issue ~!

I will fix it.
