### ISSUE TITLE
How to load video

### ISSUE THREAD

**Issue by Deamoner** [yoyota/react-posenet#28]
Maybe you have the same issue, but I can't find a similar "Video" object like the "Image" object in order to use the posenet against a video media source. Do you know how to go about doing this?

**Comment by yoyota** [comment]
I am not sure i understand what you mean.  
I use [html video element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) to load video  and pass it to network.   
tfjs posenet accept video element as image params. see this [document](https://github.com/tensorflow/tfjs-models/tree/master/posenet#params-in-estimatesinglepose)  

Below link is sample code that accept video element 
https://codesandbox.io/s/react-posenet-video-sample-wb9ns
